// Generated by Wrangler by running `wrangler types`

interface Env {
	ANIWATCH_API_DEPLOYMENT_ENV: "cloudflare-workers";
	NODE_ENV: "production";
	ANIWATCH_API_S_MAXAGE: "300";
	ANIWATCH_API_STALE_WHILE_REVALIDATE: "60";
	ANIWATCH_API_WINDOW_MS: "1800000";
	ANIWATCH_API_MAX_REQS: "1000";
	outdir: "dist";
}
