version: 1
services:
  - name: anifox-api
    type: combined
    deployment:
      instances: 1
    ports:
      - name: http
        port: 8080
        protocol: http
        public: true
    build:
      engine: dockerfile
      dockerfile: server/Dockerfile
      context: /
    environment:
      NODE_ENV: production
      CORS_ORIGIN: https://anifoxwatch.web.app
