import { Router, Request, Response } from 'express';
import { sourceManager } from '../services/source-manager.js';
import { anilistService } from '../services/anilist-service.js';
import { getHeroSpotlightCached, invalidateHeroSpotlightCache } from '../services/hero-spotlight-service.js';
import { logger, createRequestContext, PerformanceTimer } from '../utils/logger.js';
import { resolveHentaiSlug, isLikelyHentai } from '../services/hentai-resolver-service.js';
import { searchCache } from '../lib/memory-cache.js';

const router = Router();

/**
 * @route GET /api/anime/resolve-slug
 * @query slug - Anime slug (e.g., "attack-on-titan")
 * @query mode - Search mode: 'safe', 'mixed', or 'adult' (default: 'safe')
 * @description Resolve anime slug to internal ID using our database systems
 */
router.get('/resolve-slug', async (req: Request, res: Response): Promise<void> => {
    try {
        const { slug, mode = 'safe' } = req.query;
        
        if (!slug || typeof slug !== 'string') {
            res.status(400).json({ error: 'Slug parameter is required' });
            return;
        }

        // ── Fast path: slug ends with a numeric AniList ID ────────────────────
        // URLs generated by generateWatchUrl() look like "chainsaw-man-127230".
        // Detect trailing 4-9 digit number and return anilist-XXXXX immediately.
        const trailingNumMatch = slug.match(/-(\d{4,9})$/);
        if (trailingNumMatch) {
            const anilistId = `anilist-${trailingNumMatch[1]}`;
            logger.debug(`[AnimeRoutes] AniList ID fast-path: ${slug} → ${anilistId}`);
            const result = { id: anilistId, title: slug.replace(/-\d+$/, '').replace(/-/g, ' '), source: 'anilist' };
            searchCache.set(`resolve-slug:${slug}:${mode}`, result, 60 * 60 * 1000); // 1h
            res.json(result);
            return;
        }

        // Check cache first for instant response
        const cacheKey = `resolve-slug:${slug}:${mode}`;
        const cached = searchCache.get(cacheKey);
        if (cached) {
            logger.debug(`[AnimeRoutes] Cache hit for slug resolution: ${slug}`);
            res.json(cached);
            return;
        }

        // Fast, non-blocking hentai detection using local string matching only
        // This avoids API calls that cause blocking while still routing hentai correctly
        const slugLower = slug.toLowerCase();
        const likelyHentai = isLikelyHentai(slugLower);
        
        // Auto-detect hentai and set mode to adult if needed
        const effectiveMode = (likelyHentai || mode === 'adult') ? 'adult' : mode;
        
        // Use hentai resolver for likely hentai content (with timeout protection)
        if (effectiveMode === 'adult' && likelyHentai) {
            try {
                const hentaiResult = await Promise.race([
                    resolveHentaiSlug(slug),
                    new Promise<{ id: string; title: string; source: string } | null>((_, reject) => 
                        setTimeout(() => reject(new Error('Hentai resolver timeout')), 2000)
                    )
                ]);
                
                if (hentaiResult) {
                    const result = {
                        id: hentaiResult.id,
                        title: hentaiResult.title,
                        source: hentaiResult.source
                    };
                    
                    // Cache the hentai result
                    searchCache.set(cacheKey, result, 15 * 60 * 1000); // 15 minutes
                    
                    res.json(result);
                    return;
                }
            } catch (error) {
                logger.warn('Hentai resolver failed or timed out, falling back to regular search', undefined, 'AnimeRoutes');
            }
        }

        // Fallback to regular search for non-hentai or if hentai resolution fails
        let searchMode = (mode as 'safe' | 'mixed' | 'adult');
        if (searchMode !== 'safe' && searchMode !== 'mixed' && searchMode !== 'adult') {
            searchMode = 'safe';
        }

        // Try to find anime by searching for the slug
        const slugParts = slug.split('-');
        const searchTerms = [
            slug, // Full slug
            slugParts.slice(0, 3).join('-'), // First 3 words
            slugParts.slice(0, 2).join('-'), // First 2 words
            slugParts.slice(0, 4).join('-'), // First 4 words for better specificity
            slugParts.slice(0, 2).join(' '), // First 2 words with space
        ];
        
        let allCandidates: any[] = [];
        
        // Search in the specified mode
        for (const searchTerm of searchTerms) {
            const searchResults = await sourceManager.search(searchTerm, 1, undefined, { mode: searchMode });
            
            if (searchResults.results && searchResults.results.length > 0) {
                const slugLowerClean = searchTerm.toLowerCase().replace(/-/g, ' ');
                
                // Score each result based on multiple factors
                const scoredResults = searchResults.results.map(anime => {
                    // Collect all title variants for better matching
                    const titleVariants = [
                        anime.title,
                        anime.titleEnglish,
                        anime.titleRomaji,
                        anime.titleJapanese
                    ].filter(Boolean);
                    
                    // Calculate best score across all title variants
                    let bestScore = 0;
                    let bestTitle = '';
                    
                    for (const title of titleVariants) {
                        if (!title) continue; // Skip undefined titles
                        const titleLower = title.toLowerCase().replace(/[^a-z0-9\s]/g, '');
                        const slugWords = slugLowerClean.split(' ').filter(w => w.length > 2);
                        const titleWords = titleLower.split(' ').filter(w => w.length > 2);
                        
                        // Word overlap score
                        const matchCount = slugWords.filter(w => titleWords.includes(w)).length;
                        const wordScore = matchCount / Math.max(slugWords.length, 1);
                        
                        // Length similarity (prefer titles of similar length)
                        const lengthDiff = Math.abs(slugLowerClean.length - titleLower.length);
                        const lengthScore = 1 - (lengthDiff / Math.max(slugLowerClean.length, titleLower.length));
                        
                        // Sequence matching (bonus for words in similar order)
                        let sequenceScore = 0;
                        let positionBonus = 0;
                        
                        if (matchCount >= 2) {
                            let matchedSequences = 0;
                            for (let i = 0; i < slugWords.length - 1; i++) {
                                const currentIdx = titleWords.indexOf(slugWords[i]);
                                const nextIdx = titleWords.indexOf(slugWords[i + 1]);
                                if (currentIdx !== -1 && nextIdx !== -1 && nextIdx > currentIdx) {
                                    matchedSequences++;
                                }
                            }
                            sequenceScore = matchedSequences / Math.max(slugWords.length - 1, 1);
                        }
                        
                        // Position bonus for words in similar positions
                        for (let i = 0; i < slugWords.length; i++) {
                            const titleIndex = titleWords.indexOf(slugWords[i]);
                            if (titleIndex !== -1 && Math.abs(i - titleIndex) <= 1) {
                                positionBonus += 0.1;
                            }
                        }
                        
                        // Combined score with improved weighting:
                        // - 40% word overlap (reduced from 50%)
                        // - 30% sequence matching (increased from 20%)
                        // - 20% length similarity
                        // - 10% position bonus
                        let combinedScore = (wordScore * 0.4) + (sequenceScore * 0.3) + (lengthScore * 0.2) + (Math.min(positionBonus, 0.5) * 0.1);
                        
                        // Penalty for very short titles that match partially
                        if (titleWords.length < 3 && slugWords.length >= 4) {
                            combinedScore *= 0.7;
                        }
                        
                        // Bonus for longer, more comprehensive matches
                        if (matchCount >= 3 && titleWords.length >= 4) {
                            combinedScore *= 1.1;
                        }
                        
                        if (combinedScore > bestScore) {
                            bestScore = combinedScore;
                            bestTitle = title || '';
                        }
                    }
                    
                    return { anime, score: bestScore, matchedTitle: bestTitle, mode: searchMode };
                });
                
                allCandidates.push(...scoredResults);
            }
        }
        
        // Pick the best match from all candidates
        const sortedCandidates = allCandidates.sort((a, b) => b.score - a.score);
        
        if (sortedCandidates.length > 0) {
            const bestMatch = sortedCandidates[0].anime;
            if (sortedCandidates[0].score > 0.3) { // Adjusted threshold for new scoring
                const result = {
                    id: bestMatch.id,
                    title: bestMatch.title,
                    image: bestMatch.image || bestMatch.poster,
                    source: bestMatch.source,
                    genres: bestMatch.genres || []
                };
                
                // Cache the result for future requests
                searchCache.set(cacheKey, result, 15 * 60 * 1000); // 15 minutes
                
                res.json(result);
                return;
            }
        }
        
        // If not found in sources, try to create a searchable ID from the slug
        const fallbackResult = {
            id: slug, // Use slug as ID fallback
            title: slug.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase()),
            image: '',
            source: 'slug-fallback'
        };
        
        // Cache even fallback results (shorter TTL)
        searchCache.set(cacheKey, fallbackResult, 5 * 60 * 1000); // 5 minutes
        
        res.json(fallbackResult);
    } catch (error) {
        logger.error('Slug resolution error', error as Error, {}, 'AnimeRoutes');
        res.status(500).json({ error: 'Failed to resolve slug' });
    }
});

/**
 * @route GET /api/anime/search
 * @query q - Search query string
 * @query page - Page number (default: 1)
 * @query source - Preferred source (optional)
 */
router.get('/search', async (req: Request, res: Response): Promise<void> => {
    const timer = new PerformanceTimer('Anime Search', createRequestContext(req));
    try {
        const { q, page = '1', source, mode = 'safe' } = req.query;

        if (!q || typeof q !== 'string') {
            res.status(400).json({
                error: 'Query parameter "q" is required',
                results: [],
                totalPages: 0,
                currentPage: 1,
                hasNextPage: false
            });
            return;
        }

        const pageNum = parseInt(page as string, 10) || 1;
        const query = q.trim();
        let searchMode = (mode as 'safe' | 'mixed' | 'adult');

        const adultSources = ['watchhentai', 'hanime', 'akih'];
        if (source && adultSources.includes((source as string).toLowerCase())) {
            searchMode = 'adult';
        }

        logger.info(`🔍 Search: "${query}" page ${pageNum} source: ${source || 'auto'} mode: ${searchMode}`,
            { query, page: pageNum, source: source as string | undefined, mode: searchMode }, 'AnimeRoutes');

        const result = await sourceManager.search(query, pageNum, source as string | undefined, { mode: searchMode });

        const duration = timer.end();
        logger.info(`✅ Search completed: "${query}" returned ${result.results?.length || 0} results in ${duration}ms`,
            { query, page: pageNum, source: source as string | undefined, mode: searchMode, duration, results: result.results?.length }, 'AnimeRoutes');

        const totalResults = result.results?.length ? result.results.length * (result.totalPages || 1) : 0;
        res.json({
            results: result.results || [],
            totalPages: result.totalPages || 0,
            currentPage: result.currentPage || pageNum,
            hasNextPage: result.hasNextPage || false,
            totalResults,
            source: result.source || 'unknown'
        });
    } catch (error) {
        const duration = timer.end();
        const { q } = req.query;
        logger.error(`❌ Search error for "${q}"`, error as Error,
            { query: q, duration }, 'AnimeRoutes');

        const errorMessage = error instanceof Error ? error.message : 'Unknown error';
        const isTimeout = errorMessage.includes('timeout');

        res.status(isTimeout ? 504 : 500).json({
            error: isTimeout ? 'Search timed out. Please try again.' : 'Search failed. Please try again.',
            details: process.env.NODE_ENV === 'development' ? errorMessage : undefined,
            results: [],
            totalPages: 0,
            currentPage: 1,
            hasNextPage: false,
            retryAfter: 5
        });
    }
});

/**
 * @route GET /api/anime/search-all
 * @query q - Search query string
 * @query page - Page number (default: 1)
 */
router.get('/search-all', async (req: Request, res: Response): Promise<void> => {
    try {
        const { q, page = '1' } = req.query;

        if (!q || typeof q !== 'string') {
            res.status(400).json({ error: 'Query parameter "q" is required' });
            return;
        }

        const pageNum = parseInt(page as string, 10) || 1;
        const result = await sourceManager.searchAll(q, pageNum);
        res.json(result);
    } catch (error) {
        console.error('Search-all error:', error);
        res.status(500).json({ error: 'Internal server error' });
    }
});

/**
 * @route GET /api/anime/resolve
 * @query id - AniList id in the form "anilist-12345"
 * @description Resolve AniList entries to a playable streaming id when available.
 */
router.get('/resolve', async (req: Request, res: Response): Promise<void> => {
    try {
        const id = String(req.query.id || '').trim();
        const m = /^anilist-(\d+)$/i.exec(id);
        if (!m) {
            res.status(400).json({ error: 'Query parameter "id" must be an AniList id (anilist-12345)' });
            return;
        }
        const numericId = parseInt(m[1], 10);
        if (!Number.isFinite(numericId)) {
            res.status(400).json({ error: 'Invalid AniList id' });
            return;
        }

        const streamingId = await Promise.race([
            sourceManager.resolveAniListToStreamingId(numericId),
            new Promise<null>((_, reject) => setTimeout(() => reject(new Error('Resolve timeout')), 60000))
        ]);
        if (!streamingId) {
            res.status(404).json({ error: 'No streaming match found', id });
            return;
        }

        res.json({ id, streamingId });
    } catch (error) {
        console.error('Resolve error:', error);
        res.status(500).json({ error: 'Internal server error' });
    }
});

/**
 * @route GET /api/anime/trending
 * @query page - Page number (default: 1)
 * @query source - Preferred source (optional)
 */
router.get('/trending', async (req: Request, res: Response): Promise<void> => {
    try {
        const { page = '1', source } = req.query;
        const pageNum = parseInt(page as string, 10) || 1;
        const result = await sourceManager.getTrending(pageNum, source as string | undefined);
        res.json({ results: result, source: source || 'default' });
    } catch (error) {
        console.error('Trending error:', error);
        res.status(500).json({ error: 'Internal server error' });
    }
});

/**
 * @route GET /api/anime/hero-spotlight
 * Home hero: AniList widescreen banners + synopsis (Jikan when AniList text is short).
 * Query refresh=1 bypasses server cache.
 */
router.get('/hero-spotlight', async (req: Request, res: Response): Promise<void> => {
    try {
        const refresh = req.query.refresh === '1' || req.query.refresh === 'true';
        if (refresh) {
            invalidateHeroSpotlightCache();
        }
        const results = await getHeroSpotlightCached();
        res.set('Cache-Control', 'public, max-age=300');
        const malOn = Boolean(
            process.env.MAL_CLIENT_ID?.trim() || process.env.MYANIMELIST_CLIENT_ID?.trim()
        );
        res.json({
            results,
            source: malOn ? 'anilist+jikan+mal' : 'anilist+jikan',
            count: results.length,
        });
    } catch (error) {
        logger.error('Hero spotlight error', error as Error, {}, 'AnimeRoutes');
        res.status(500).json({ error: 'Hero spotlight failed', results: [], count: 0 });
    }
});

/**
 * @route GET /api/anime/latest
 * @query page - Page number (default: 1)
 * @query source - Preferred source (optional)
 */
router.get('/latest', async (req: Request, res: Response): Promise<void> => {
    try {
        const { page = '1', source } = req.query;
        const pageNum = parseInt(page as string, 10) || 1;
        const result = await sourceManager.getLatest(pageNum, source as string | undefined);
        res.json({ results: result, source: source || 'default' });
    } catch (error) {
        console.error('Latest error:', error);
        res.status(500).json({ error: 'Internal server error' });
    }
});

/**
 * @route GET /api/anime/top-rated
 * @query page - Page number (default: 1)
 * @query limit - Number of results (default: 10)
 * @query source - Preferred source (optional)
 */
router.get('/top-rated', async (req: Request, res: Response): Promise<void> => {
    try {
        const { page = '1', limit = '10', source } = req.query;
        const pageNum = parseInt(page as string, 10) || 1;
        const limitNum = parseInt(limit as string, 10) || 10;

        // Use SourceManager for top rated to ensure results are playable
        const result = await sourceManager.getTopRated(pageNum, limitNum, source as string | undefined);

        res.json({ results: result, source: source || 'default', currentPage: pageNum });
    } catch (error) {
        console.error('Top-rated error:', error);
        res.status(500).json({ error: 'Internal server error' });
    }
});

/**
 * @route GET /api/anime/schedule
 * @query start_date - Start date in YYYY-MM-DD format (default: Monday of current week)
 * @query end_date - End date in YYYY-MM-DD format (default: Sunday of current week)
 * @query page - Page number (default: 1)
 * @description Get anime airing schedule for a date range from AniList with daily groupings
 */
router.get('/schedule', async (req: Request, res: Response): Promise<void> => {
    try {
        const { start_date, end_date, page = '1' } = req.query;
        const pageNum = parseInt(page as string, 10) || 1;

        console.log(`[AnimeRoutes] 📅 Fetching airing schedule, start: ${start_date || 'current week'}, end: ${end_date || 'current week'}, page ${pageNum}`);

        const result = await anilistService.getAiringSchedule(
            start_date as string | undefined,
            end_date as string | undefined,
            pageNum,
            50
        );

        // Group schedule by day of week using lowercase keys for frontend
        const groupedByDay: Record<string, typeof result.schedule> = {
            monday: [],
            tuesday: [],
            wednesday: [],
            thursday: [],
            friday: [],
            saturday: [],
            sunday: []
        };
        const dayMapping: Record<number, string> = {
            0: 'sunday',
            1: 'monday',
            2: 'tuesday',
            3: 'wednesday',
            4: 'thursday',
            5: 'friday',
            6: 'saturday'
        };

        result.schedule.forEach(item => {
            const date = new Date(item.airingAt * 1000);
            const dayName = dayMapping[date.getDay()];
            if (groupedByDay[dayName]) {
                groupedByDay[dayName].push(item);
            }
        });

        // Sort each day's schedule by air time
        Object.keys(groupedByDay).forEach(day => {
            groupedByDay[day].sort((a, b) => a.airingAt - b.airingAt);
        });

        // Calculate countdown data for each item
        const now = Date.now() / 1000;
        const scheduleWithCountdown = result.schedule.map(item => ({
            ...item,
            countdown: Math.max(0, item.airingAt - now),
            timeUntilAiring: item.airingAt - now
        }));

        res.json({
            schedule: scheduleWithCountdown,
            groupedByDay,
            metadata: {
                totalShows: result.schedule.length,
                dateRange: {
                    start: start_date || 'current-week-start',
                    end: end_date || 'current-week-end'
                },
                pageInfo: result.pageInfo
            },
            hasNextPage: result.hasNextPage,
            currentPage: pageNum
        });
    } catch (error) {
        console.error('Schedule error:', error);
        res.status(500).json({ error: 'Internal server error' });
    }
});

/**
 * @route GET /api/anime/leaderboard
 * @query page - Page number (default: 1)
 * @query type - Leaderboard type: 'trending' or 'top-rated' (default: 'trending')
 * @description Get weekly leaderboard from AniList with fallback to source manager
 */
router.get('/leaderboard', async (req: Request, res: Response): Promise<void> => {
    try {
        const { page = '1', type = 'trending' } = req.query;
        const pageNum = parseInt(page as string, 10) || 1;

        console.log(`[AnimeRoutes] 🏆 Fetching leaderboard, type: ${type}, page ${pageNum}`);

        let result;
        let source = 'AniList';
        
        try {
            if (type === 'top-rated') {
                result = await anilistService.getTopRatedAnime(pageNum, 10);
            } else {
                result = await anilistService.getTrendingThisWeek(pageNum, 10);
            }
        } catch (anilistError) {
            console.warn('[AnimeRoutes] AniList leaderboard failed, will use fallback:', anilistError);
            result = null;
        }

        // Fallback to source manager if AniList returns empty or fails
        if (!result || !result.results || result.results.length === 0) {
            console.log('[AnimeRoutes] Using source manager fallback for leaderboard');
            source = 'SourceManager';
            
            // Get trending from source manager as fallback
            const trendingResults = await sourceManager.getTrending(pageNum);
            
            // Filter out adult content for homepage leaderboard
            const filteredResults = trendingResults.filter(anime => {
                const title = anime.title?.toLowerCase() || '';
                const id = anime.id?.toLowerCase() || '';
                const genres = anime.genres?.map(g => g?.toLowerCase()) || [];
                
                return !title.includes('hentai') && 
                       !id.includes('hentai') && 
                       !id.includes('hanime') &&
                       !genres.includes('hentai');
            }).slice(0, 10);

            result = {
                results: filteredResults,
                pageInfo: {
                    hasNextPage: trendingResults.length > 10,
                    currentPage: pageNum,
                    totalCount: filteredResults.length
                }
            };
        }

        // Handle both old AnimeSearchResult and new pageInfo format
        const pageInfo = 'pageInfo' in result ? result.pageInfo : {
            hasNextPage: result.hasNextPage,
            currentPage: result.currentPage,
            totalCount: (result.results?.length || 0) * (result.totalPages || 1)
        };

        res.json({
            results: result.results,
            pageInfo: {
                hasNextPage: pageInfo.hasNextPage,
                currentPage: pageInfo.currentPage,
                totalPages: 'totalPages' in result ? result.totalPages : Math.ceil(pageInfo.totalCount / 10)
            },
            type,
            source
        });
    } catch (error) {
        console.error('Leaderboard error:', error);
        res.status(500).json({ error: 'Internal server error' });
    }
});

/**
 * @route GET /api/anime/seasonal
 * @query year - Year (default: current year)
 * @query season - Season: 'winter', 'spring', 'summer', 'fall' (default: current season)
 * @query page - Page number (default: 1)
 * @description Get seasonal anime from AniList with pagination metadata
 */
router.get('/seasonal', async (req: Request, res: Response): Promise<void> => {
    try {
        const { year, season, page = '1' } = req.query;
        const pageNum = parseInt(page as string, 10) || 1;
        const yearNum = year ? parseInt(year as string, 10) : undefined;

        console.log(`[AnimeRoutes] 🌸 Fetching seasonal anime: ${season || 'current'} ${yearNum || 'current'}, page ${pageNum}`);

        const result = await anilistService.getSeasonalAnime(yearNum, season as string | undefined, pageNum, 25);

        // Extract results and pageInfo based on the response structure
        const seasonalResult = result as {
            results: import('../types/anime.js').AnimeBase[];
            pageInfo?: { hasNextPage: boolean; currentPage: number; totalCount: number };
            seasonInfo?: { year: number; season: string };
            hasNextPage?: boolean;
            currentPage?: number;
            totalPages?: number;
        };

        res.json({
            results: seasonalResult.results,
            pageInfo: {
                hasNextPage: seasonalResult.pageInfo?.hasNextPage ?? seasonalResult.hasNextPage ?? false,
                currentPage: seasonalResult.pageInfo?.currentPage ?? seasonalResult.currentPage ?? pageNum,
                totalPages: seasonalResult.pageInfo?.totalCount
                    ? Math.ceil(seasonalResult.pageInfo.totalCount / 25)
                    : (seasonalResult.totalPages ?? 1),
                totalItems: seasonalResult.pageInfo?.totalCount ?? seasonalResult.results?.length ?? 0
            },
            seasonInfo: seasonalResult.seasonInfo ?? {
                year: yearNum ?? new Date().getFullYear(),
                season: (season as string) ?? 'current'
            },
            source: 'AniList'
        });
    } catch (error) {
        console.error('Seasonal error:', error);
        res.status(500).json({ error: 'Internal server error' });
    }
});

/**
 * @route GET /api/anime/genre/:genre
 * @param genre - Genre name
 * @query page - Page number (default: 1)
 * @query source - Preferred source (optional)
 */
router.get('/genre/:genre', async (req: Request, res: Response): Promise<void> => {
    try {
        const { genre } = req.params;
        const { page = '1', source } = req.query;

        if (!genre || typeof genre !== 'string') {
            res.status(400).json({ error: 'Genre parameter is required' });
            return;
        }

        const pageNum = parseInt(page as string, 10) || 1;
        const result = await sourceManager.getAnimeByGenre(genre, pageNum, source as string | undefined);
        res.json(result);
    } catch (error) {
        console.error('Genre search error:', error);
        res.status(500).json({ error: 'Internal server error' });
    }
});

/**
 * @route GET /api/anime/genre-anilist/:genre
 * @param genre - Genre name
 * @query page - Page number (default: 1)
 * @description Search anime by genre using AniList API (most accurate)
 */
router.get('/genre-anilist/:genre', async (req: Request, res: Response): Promise<void> => {
    try {
        const { genre } = req.params;
        const { page = '1' } = req.query;

        if (!genre || typeof genre !== 'string') {
            res.status(400).json({ error: 'Genre parameter is required' });
            return;
        }

        const pageNum = parseInt(page as string, 10) || 1;
        console.log(`[AnimeRoutes] Searching AniList for genre: ${genre}, page: ${pageNum}`);

        const result = await sourceManager.getAnimeByGenreAniList(genre, pageNum);
        res.json(result);
    } catch (error) {
        console.error('AniList genre search error:', error);
        res.status(500).json({ error: 'Internal server error' });
    }
});

/**
 * @route GET /api/anime/filter
 * @query type - Anime type (TV, Movie, OVA, ONA, Special)
 * @query genre - Genre name(s) - can be comma-separated for multiple
 * @query status - Anime status (Ongoing, Completed, Upcoming)
 * @query year - Release year
 * @query season - Season (Winter, Spring, Summer, Fall)
 * @query page - Page number (default: 1)
 * @query limit - Results per page (default: 20)
 * @query sort - Sort by (rating, year, title, episodes)
 * @query order - Sort order (asc, desc)
 * @query source - Preferred source (optional)
 */
router.get('/filter', async (req: Request, res: Response): Promise<void> => {
    try {
        const {
            type,
            genre,
            status,
            year,
            season,
            page = '1',
            limit = '20',
            sort = 'rating',
            order = 'desc',
            source
        } = req.query;

        const pageNum = parseInt(page as string, 10) || 1;
        const limitNum = parseInt(limit as string, 10) || 20;

        // Parse multiple genres if comma-separated
        const genres = genre ? (genre as string).split(',').map(g => g.trim()) : [];

        // Build filter object
        const filters = {
            type: type as string,
            genres: genres.length > 0 ? genres : undefined,
            status: status as string,
            year: year ? parseInt(year as string, 10) : undefined,
            season: season as string,
            sort: sort as string,
            order: order as string,
            limit: limitNum,
            page: pageNum,
            source: source as string
        };

        // Remove undefined filters
        Object.keys(filters).forEach(key => {
            if (filters[key as keyof typeof filters] === undefined) {
                delete filters[key as keyof typeof filters];
            }
        });

        const result = await sourceManager.getFilteredAnime(filters);
        res.json({
            results: result.anime || [],
            currentPage: pageNum,
            totalPages: result.totalPages || 1,
            hasNextPage: result.hasNextPage || false,
            totalResults: result.totalResults || 0,
            filters: filters,
            source: source || 'default'
        });
    } catch (error) {
        console.error('Filter error:', error);
        res.status(500).json({ error: 'Internal server error' });
    }
});

/**
 * @route GET /api/anime/browse
 * @query type - Anime type (TV, Movie, OVA, ONA, Special)
 * @query genre - Genre name(s) - comma-separated for multiple
 * @query status - Anime status (Ongoing, Completed, Upcoming)
 * @query year - Release year
 * @query startYear - Start year for date range filter
 * @query endYear - End year for date range filter
 * @query page - Page number (default: 1)
 * @query limit - Results per page (default: 25)
 * @query sort - Sort by (popularity, trending, recently_released, shuffle, rating, year, title)
 * @query order - Sort order (asc, desc) - default desc
 * @query source - Preferred source (optional)
 */
router.get('/browse', async (req: Request, res: Response): Promise<void> => {
    const startTime = Date.now();
    try {
        const {
            type,
            genre,
            genres,
            status,
            year,
            startYear,
            endYear,
            page = '1',
            limit = '25',
            sort = 'popularity',
            order = 'desc',
            source,
            mode = 'safe'
        } = req.query;

        const pageNum = parseInt(page as string, 10) || 1;
        const limitNum = parseInt(limit as string, 10) || 25;

        const genreParam = (genres as string) || (genre as string);
        const parsedGenres = genreParam ? genreParam.split(',').map(g => g.trim()) : [];
        let browseMode = (mode as 'safe' | 'mixed' | 'adult');

        const adultSources = ['watchhentai', 'hanime', 'akih'];
        const adultGenresSet = new Set(['hentai', 'ecchi', 'yaoi', 'yuri']);
        if (source && adultSources.includes((source as string).toLowerCase())) {
            browseMode = 'adult';
        } else if (parsedGenres.some(g => adultGenresSet.has(g.toLowerCase()))) {
            browseMode = 'adult';
        }

        console.log(`[AnimeRoutes] 📋 Browse: type=${type || 'all'} genres=${parsedGenres.join(',') || 'none'} sort=${sort} mode=${browseMode}`);

        // We no longer shortcut to AniList for genre searches as it returned results without streaming providers.
        // Falling through to browseAnime handles this using source-native methods or AniList with instant matching.

        const filters = {
            type: type as string,
            genres: parsedGenres.length > 0 ? parsedGenres : undefined,
            status: status as string,
            year: year ? parseInt(year as string, 10) : undefined,
            startYear: startYear ? parseInt(startYear as string, 10) : undefined,
            endYear: endYear ? parseInt(endYear as string, 10) : undefined,
            sort: sort as string,
            order: order as string,
            limit: limitNum,
            page: pageNum,
            source: source as string,
            mode: browseMode
        };

        Object.keys(filters).forEach(key => {
            if (filters[key as keyof typeof filters] === undefined) {
                delete filters[key as keyof typeof filters];
            }
        });

        const result = await sourceManager.browseAnime(filters);
        const duration = Date.now() - startTime;
        console.log(`[AnimeRoutes] ✅ Browse completed: ${result.anime?.length || 0} results in ${duration}ms`);

        res.json({
            results: result.anime || [],
            currentPage: pageNum,
            totalPages: result.totalPages || 1,
            hasNextPage: result.hasNextPage || false,
            totalResults: result.totalResults || result.anime?.length || 0,
            filters: { type, genre, status, year, startYear, endYear, sort, order },
            source: source || 'default'
        });
    } catch (error) {
        const duration = Date.now() - startTime;
        console.error(`[AnimeRoutes] ❌ Browse error after ${duration}ms:`, error);

        const errorMessage = error instanceof Error ? error.message : 'Unknown error';
        const isTimeout = errorMessage.includes('timeout');

        res.status(isTimeout ? 504 : 500).json({
            error: isTimeout ? 'Browse operation timed out' : 'Internal server error',
            details: process.env.NODE_ENV === 'development' ? errorMessage : undefined,
            results: [],
            currentPage: 1,
            totalPages: 0,
            hasNextPage: false,
            retryAfter: 5
        });
    }
});

/**
 * @route GET /api/anime/types
 * @description Get all available anime types
 */
router.get('/types', async (req: Request, res: Response): Promise<void> => {
    try {
        const types = [
            { value: 'TV', label: 'TV Series', description: 'Television series' },
            { value: 'Movie', label: 'Movies', description: 'Feature films' },
            { value: 'OVA', label: 'OVAs', description: 'Original Video Animation' },
            { value: 'ONA', label: 'ONAs', description: 'Original Net Animation' },
            { value: 'Special', label: 'Specials', description: 'Special episodes' }
        ];

        res.json({ types });
    } catch (error) {
        console.error('Types error:', error);
        res.status(500).json({ error: 'Internal server error' });
    }
});

/**
 * @route GET /api/anime/genres
 * @description Get all available genres
 */
router.get('/genres', async (req: Request, res: Response): Promise<void> => {
    try {
        // Comprehensive list of anime genres
        const genres = [
            'Action', 'Adventure', 'Comedy', 'Drama', 'Fantasy', 'Horror', 'Mystery', 'Romance',
            'Sci-Fi', 'Slice of Life', 'Sports', 'Supernatural', 'Thriller', 'Yuri', 'Yaoi',
            'Ecchi', 'Harem', 'Mecha', 'Music', 'Psychological', 'Historical', 'Parody',
            'Samurai', 'Shounen', 'Shoujo', 'Seinen', 'Josei', 'Kids', 'Police', 'Military',
            'School', 'Demons', 'Game', 'Magic', 'Vampire', 'Space', 'Martial Arts',
            'Isekai', 'Gore', 'Survival', 'Cyberpunk', 'Super Power', 'Mythology',
            'Work Life', 'Adult Cast', 'Anthropomorphic', 'CGDCT', 'Childcare', 'Combat Sports',
            'Crossdressing', 'Delinquents', 'Detective', 'Educational', 'Gag Humor', 'Gender Bender',
            'Gore', 'High Stakes Game', 'Idols (Female)', 'Idols (Male)', 'Isekai', 'Iyashikei',
            'Love Polygon', 'Magical Sex Shift', 'Mahou Shoujo', 'Medical', 'Memoir', 'Mythology',
            'Organized Crime', 'Otaku Culture', 'Performing Arts', 'Pets', 'Reincarnation', 'Reverse Harem',
            'Romantic Subtext', 'Showbiz', 'Space', 'Strategy Game', 'Super Power', 'Survival',
            'Team Sports', 'Time Travel', 'Vampire', 'Video Game', 'Visual Arts', 'Workplace'
        ];

        // Remove duplicates and sort alphabetically
        const uniqueGenres = [...new Set(genres)].sort();

        res.json({ genres: uniqueGenres });
    } catch (error) {
        console.error('Genres error:', error);
        res.status(500).json({ error: 'Internal server error' });
    }
});

/**
 * @route GET /api/anime/statuses
 * @description Get all available statuses
 */
router.get('/statuses', async (req: Request, res: Response): Promise<void> => {
    try {
        const statuses = [
            { value: 'Ongoing', label: 'Ongoing', description: 'Currently airing' },
            { value: 'Completed', label: 'Completed', description: 'Finished airing' },
            { value: 'Upcoming', label: 'Upcoming', description: 'Not yet aired' }
        ];

        res.json({ statuses });
    } catch (error) {
        console.error('Statuses error:', error);
        res.status(500).json({ error: 'Internal server error' });
    }
});

/**
 * @route GET /api/anime/seasons
 * @description Get all available seasons
 */
router.get('/seasons', async (req: Request, res: Response): Promise<void> => {
    try {
        const seasons = [
            { value: 'Winter', label: 'Winter', months: 'Jan, Feb, Mar' },
            { value: 'Spring', label: 'Spring', months: 'Apr, May, Jun' },
            { value: 'Summer', label: 'Summer', months: 'Jul, Aug, Sep' },
            { value: 'Fall', label: 'Fall', months: 'Oct, Nov, Dec' }
        ];

        res.json({ seasons });
    } catch (error) {
        console.error('Seasons error:', error);
        res.status(500).json({ error: 'Internal server error' });
    }
});

/**
 * @route GET /api/anime/years
 * @description Get available years (current year back to 1970)
 */
router.get('/years', async (req: Request, res: Response): Promise<void> => {
    try {
        const currentYear = new Date().getFullYear();
        const years = [];

        for (let year = currentYear; year >= 1970; year--) {
            years.push({
                value: year,
                label: year.toString(),
                decade: `${Math.floor(year / 10) * 10}s`
            });
        }

        res.json({ years });
    } catch (error) {
        console.error('Years error:', error);
        res.status(500).json({ error: 'Internal server error' });
    }
});

/**
 * @route GET /api/anime/random
 * @query source - Preferred source (optional)
 */
router.get('/random', async (req: Request, res: Response): Promise<void> => {
    try {
        const { source } = req.query;
        const result = await sourceManager.getRandomAnime(source as string | undefined);

        if (!result) {
            res.status(404).json({ error: 'No random anime found' });
            return;
        }

        res.json(result);
    } catch (error) {
        console.error('Random anime error:', error);
        res.status(500).json({ error: 'Internal server error' });
    }
});

/**
 * @route GET /api/anime
 * @query id - Anime ID (as query param to handle IDs with /)
 */
router.get('/', async (req: Request, res: Response): Promise<void> => {
    try {
        const id = req.query.id as string;

        if (!id) {
            res.status(400).json({ error: 'Query parameter "id" is required' });
            return;
        }

        const result = await Promise.race([
            sourceManager.getAnime(id),
            new Promise<null>((_, reject) => setTimeout(() => reject(new Error('Get anime timeout')), 25000))
        ]);

        if (!result) {
            res.status(404).json({ error: 'Anime not found' });
            return;
        }

        res.json(result);
    } catch (error) {
        console.error('Get anime error:', error);
        res.status(500).json({ error: 'Internal server error' });
    }
});

/**
 * @route GET /api/anime/:id
 * @param id - Anime ID
 * @deprecated Use GET /api/anime?id=... instead for IDs with / characters
 */
router.get('/episodes', async (req: Request, res: Response): Promise<void> => {
    try {
        const id = req.query.id as string;

        if (!id) {
            res.status(400).json({ error: 'Query parameter "id" is required' });
            return;
        }

        // Disable caching for episodes to ensure fresh data
        res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
        res.setHeader('Pragma', 'no-cache');
        res.setHeader('Expires', '0');

        const result = await Promise.race([
            sourceManager.getEpisodes(id),
            new Promise<any[]>((_, reject) => setTimeout(() => reject(new Error('Get episodes timeout')), 60000))
        ]);
        
        // Log episode IDs for debugging
        console.log(`[Episodes API] Returning ${result.length} episodes for ${id}:`, result.map((e: any) => ({ id: e.id, number: e.number })));
        
        res.json({ episodes: result });
    } catch (error) {
        console.error('Get episodes error:', error);
        res.status(500).json({ error: 'Internal server error' });
    }
});

/**
 * @route GET /api/anime/:id
 * @param id - Anime ID
 * @deprecated Use GET /api/anime?id=... instead for IDs with / characters
 */
router.get('/:id', async (req: Request, res: Response): Promise<void> => {
    try {
        // Decode the ID - Express doesn't automatically decode URL-encoded params
        const id = decodeURIComponent(req.params.id as string);
        const result = await sourceManager.getAnime(id);

        if (!result) {
            res.status(404).json({ error: 'Anime not found' });
            return;
        }

        res.json(result);
    } catch (error) {
        console.error('Get anime error:', error);
        res.status(500).json({ error: 'Internal server error' });
    }
});

/**
 * @route GET /api/anime/:id/episodes
 * @param id - Anime ID
 * @deprecated Use GET /api/anime/episodes?id=... instead for IDs with / characters
 */
router.get('/:id/episodes', async (req: Request, res: Response): Promise<void> => {
    try {
        // Decode the ID - Express doesn't automatically decode URL-encoded params
        const id = decodeURIComponent(req.params.id as string);
        const result = await sourceManager.getEpisodes(id);
        res.json({ episodes: result });
    } catch (error) {
        console.error('Get episodes error:', error);
        res.status(500).json({ error: 'Internal server error' });
    }
});

export default router;
